Repository 2023SVBootcamp-Team-H/backend, pull requests merged in 2023-07, with the labels that each got.

#6 Be/ #1 vscode setting & docker-compose
  .gitignore
  data/grafana/env.grafana
  data/mysql/env.mysql
  data/python/.dockerignore
  data/python/Dockerfile
  data/python/README.md
  data/python/docker-compose.yml
  data/python/requirements.txt
  docker-compose.yml
  test/test.txt
Labels: 환경 설정

#12 BE / #11 DJango Setting
  .gitignore
  data/python/dontworry/config/__init__.py
  data/python/dontworry/config/asgi.py
  data/python/dontworry/config/settings.py
  data/python/dontworry/config/urls.py
  data/python/dontworry/config/wsgi.py
  data/python/dontworry/manage.py
  data/python/manage.py
  data/python/requirements.txt
Labels: 기능 구현

#14 Prometheus + Grafana + Docker
  data/grafana/desktop.ini
  data/prometheus/config/prometheus.yml
  data/prometheus/config/rule.yml
  data/python/Dockerfile
  docker-compose.yml
Labels: 기능 구현

#16 Server_Script
  data/prometheus/config/prometheus.yml
  docker-compose.yml
  server_script.sh
Labels: 기능 구현

#22 BE / #18 / Docker + Nginx
  data/nginx/Dockerfile
  data/nginx/conf.d/default.conf
  data/nginx/html/index.html
  data/nginx/nginx.conf
  docker-compose.yml
Labels: 기능 구현

#25 chore : gitignore 설정
  .gitignore
Labels: 환경 설정

#30 BE / #29 Docker + Django
  data/django_project/Dockerfile
  data/django_project/manage.py
  data/prometheus/config/prometheus.yml
  docker-compose.yml
Labels: 기능 구현

#34 fix: prometheus.yml파일 내부 targets 수정
  data/prometheus/config/prometheus.yml
Labels: 오류 수정

#35 feat: Docker + Redis
  docker-compose.yml
Labels: 기능 구현

#47 feat : cAdvisor 구현 및 docker-compose.yml 수정
  .gitignore
  README.md
  data/prometheus/config/prometheus.yml
  docker-compose.monitor.yml
  docker-compose.prod.yml
  docker-compose.yml
  monitoring_init.sh
  monitoring_refresh.sh
  server_init.sh
  server_refresh.sh
Labels: 기능 구현

#51 fix: logstash.conf indentation 수정 4 -> 2
  ELK/filebeat/config/filebeat.yml
  ELK/logstash/pipeline/logstash.conf
Labels: 오류 수정

#53 feat: Nginx https -> http proxy 연결
  data/nginx/nginx.conf
Labels: 기능 구현

#55 refact: docker-compose network 설정
  docker-compose.logging.yml
  docker-compose.prod.yml
  docker-compose.yml
Labels: 리팩토링
